# Generated by Django 3.0.3 on 2020-03-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('publisher', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Overlays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('publisher', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('scenarios', models.TextField(max_length=255)),
                ('maps', models.CharField(blank=True, max_length=255)),
                ('overlays', models.CharField(blank=True, max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('date', models.CharField(max_length=64)),
                ('publisher', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('maps', models.CharField(blank=True, max_length=255)),
                ('overlays', models.CharField(blank=True, max_length=255)),
                ('sides', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('time', models.CharField(max_length=64)),
                ('source', models.TextField(max_length=255)),
                ('front', models.TextField(max_length=255)),
            ],
        ),
    ]
